-- CRIANDO UMA BASE DE DADOS CHAMADA SCRIPT
CREATE DATABASE SCRIPT;
-- UTILIZANDO A BASE DE DADOS SCRIPT
USE SCRIPT;
-- CRIANDO A NOSSA PRIMERIA TABELA
CREATE TABLE clientes (
	id INT PRIMARY KEY,
	nome VARCHAR(50),
	email VARCHAR(100)
)
-- INSERINDO VALORES NA NOSSA TABELA
INSERT INTO clientes VALUES (
	1,
	'Leonardo',
	'leonardo@fatec.com'
)
-- FAZENDO A AMOSTRAGEM DO CONTEÚDO DA TABELA
SELECT * FROM clientes